{
  "formatVersion": "1.1",
  "component": {
    "group": "org.sic",
    "module": "sic_core",
    "version": "1.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "sic_core-1.2-plain.jar",
          "url": "sic_core-1.2-plain.jar",
          "size": 29398,
          "sha512": "3dda4366f3ff33110e37b83ce2045e68e185a5c847031d569c54a0e9ef7ed9ba2f47b8f666853206d15272edca563d0a2b1760f1600b1cedd583993a70997956",
          "sha256": "1341a4230828c3a3c27b631b699339a7990cb16227b4896e99d7ebdc99cb8eda",
          "sha1": "9ba366eb3508a6a2f076b9220d09309f2d8447a1",
          "md5": "e0c3b5e1153124cfa062d72a1e3fea92"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-aop"
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-validation"
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-configuration-processor"
        },
        {
          "group": "org.projectlombok",
          "module": "lombok"
        },
        {
          "group": "cn.hutool",
          "module": "hutool-all"
        },
        {
          "group": "com.alibaba",
          "module": "fastjson",
          "version": {
            "requires": "1.2.83"
          }
        }
      ],
      "files": [
        {
          "name": "sic_core-1.2-plain.jar",
          "url": "sic_core-1.2-plain.jar",
          "size": 29398,
          "sha512": "3dda4366f3ff33110e37b83ce2045e68e185a5c847031d569c54a0e9ef7ed9ba2f47b8f666853206d15272edca563d0a2b1760f1600b1cedd583993a70997956",
          "sha256": "1341a4230828c3a3c27b631b699339a7990cb16227b4896e99d7ebdc99cb8eda",
          "sha1": "9ba366eb3508a6a2f076b9220d09309f2d8447a1",
          "md5": "e0c3b5e1153124cfa062d72a1e3fea92"
        }
      ]
    }
  ]
}
