{
  "formatVersion": "1.1",
  "component": {
    "group": "org.sic",
    "module": "sic_core",
    "version": "1.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "sic_core-1.1-plain.jar",
          "url": "sic_core-1.1-plain.jar",
          "size": 29398,
          "sha512": "90a73261e24e527bde5e9047a7d16f41fb5cb918c2619cf604fead38d7e31d0e206eec81d4290a4607e6109f14dc01af4e62afcf7bc58fa41b11aa87e5b0b6b2",
          "sha256": "b5596dcf20ad17bf620ab4ee264ee175921dd580c4c28db505f77abc32cd16ca",
          "sha1": "847ce1b5e843f496122f6542840dac1d27f40775",
          "md5": "a739af9184019e11ff285f323ae27c27"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-aop"
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-validation"
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-configuration-processor"
        },
        {
          "group": "org.projectlombok",
          "module": "lombok"
        },
        {
          "group": "cn.hutool",
          "module": "hutool-all"
        },
        {
          "group": "com.alibaba",
          "module": "fastjson",
          "version": {
            "requires": "1.2.83"
          }
        }
      ],
      "files": [
        {
          "name": "sic_core-1.1-plain.jar",
          "url": "sic_core-1.1-plain.jar",
          "size": 29398,
          "sha512": "90a73261e24e527bde5e9047a7d16f41fb5cb918c2619cf604fead38d7e31d0e206eec81d4290a4607e6109f14dc01af4e62afcf7bc58fa41b11aa87e5b0b6b2",
          "sha256": "b5596dcf20ad17bf620ab4ee264ee175921dd580c4c28db505f77abc32cd16ca",
          "sha1": "847ce1b5e843f496122f6542840dac1d27f40775",
          "md5": "a739af9184019e11ff285f323ae27c27"
        }
      ]
    }
  ]
}
