{
  "formatVersion": "1.1",
  "component": {
    "group": "com.lckj.sic",
    "module": "sic_core",
    "version": "1.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "sic_core-1.4-plain.jar",
          "url": "sic_core-1.4-plain.jar",
          "size": 29398,
          "sha512": "89430541c0e2e446cb7a8594348ff50db9fe16ae0e28b1c14bf8ca446cf232e5a79f76d96e5acfaa6b0642ab78afbf802c5031ccbf6988f94ff329315437d5b3",
          "sha256": "02f2e378a27daca36bfafeef68e3cb78bcfbb86a5dea303662a9b4e0aa37b8bb",
          "sha1": "cdf8b34ea2420605b861e5772a555ae4618b13f6",
          "md5": "6bafb54d6339c6139b9015a5ccbfde87"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-aop"
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-validation"
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-configuration-processor"
        },
        {
          "group": "org.projectlombok",
          "module": "lombok"
        },
        {
          "group": "cn.hutool",
          "module": "hutool-all"
        },
        {
          "group": "com.alibaba",
          "module": "fastjson",
          "version": {
            "requires": "1.2.83"
          }
        }
      ],
      "files": [
        {
          "name": "sic_core-1.4-plain.jar",
          "url": "sic_core-1.4-plain.jar",
          "size": 29398,
          "sha512": "89430541c0e2e446cb7a8594348ff50db9fe16ae0e28b1c14bf8ca446cf232e5a79f76d96e5acfaa6b0642ab78afbf802c5031ccbf6988f94ff329315437d5b3",
          "sha256": "02f2e378a27daca36bfafeef68e3cb78bcfbb86a5dea303662a9b4e0aa37b8bb",
          "sha1": "cdf8b34ea2420605b861e5772a555ae4618b13f6",
          "md5": "6bafb54d6339c6139b9015a5ccbfde87"
        }
      ]
    }
  ]
}
